mysql:
  host: 127.0.0.1
  port: 3306
  db: go_admin
  user: root
  password: 123456789
  log-level: dev

system:
  host: 0.0.0.0
  port: 8080
  # debug | release | test
  env: debug

logger:
  level: info
  prefix: '[go-admin]'
  director: log
  show-line: true
  log-in-console: true

